apiVersion: v1
kind: Service
metadata:
  name: personio-challenge
spec:
  type: LoadBalancer
  selector:
    app: personio-challenge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personio-challenge
spec:
  replicas: 12
  selector:
    matchLabels:
      app: personio-challenge
  template:
    metadata:
      labels:
        app: personio-challenge
    spec:
      containers:
        - name: personio-challenge
          image: 249422412389.dkr.ecr.eu-west-1.amazonaws.com/dmur-challenge:latest
          ports:
            - containerPort: 8080
          env:
            - name: HELLO
              value: "Welcome"
          imagePullPolicy: Always